### ISSUE TITLE
JRuby 9.0.0.0 support?

### ISSUE THREAD

**Issue by skydan** [rsim/mondrian-olap#30]
Does it make sense to wait for jruby 9.0 support in near future?

**Comment by rsim** [comment]
Have you tried to use it with JRuby 9.0 and got some problems? If yes then please report them.

I haven't yet tested it with JRuby 9.0 but will try to do it in the nearest future.

**Comment by skydan** [comment]
Not yet just wondering. Will test it soon and let you know.

**Comment by skydan** [comment]
Works fine!
