### ISSUE TITLE
No Support for Mondrian Attributes

### ISSUE THREAD

**Issue by ckmorris** [rsim/mondrian-olap#31]
As of Version 4 Mondrian has supported the concept of Attributes: http://mondrian.pentaho.com/schema.html#Attributes_versus_Hierarchies

I have been unable to find support for these Attributes in the code base. Is there a workaround solution or will you be able to add support for this functionality?

**Comment by rsim** [comment]
I am closing this as there are no plans for Mondrian 4 support now.
