### ISSUE TITLE
Mondrian 4?

### ISSUE THREAD

**Issue by jazzido** [rsim/mondrian-olap#41]
Hi @rsim,

Do you have plans to support Mondrian 4 in `mondrian-olap`?

**Comment by rsim** [comment]
We (at https://eazybi.com) currently do not plan to upgrade to Mondrian 4 as it has a different schema definition and it would be too painful for us to migrate to it. And I suspect that majority of Pentaho customers are also using Mondrian 3.x so these two parallel branches will be still supported for some while.

But if you are interested in Mondrian 4.x then you can try to create an experimental branch and see if it would be possible to do a single `mondrian-olap` version which could dynamically switch to either Mondrian 3 or Mondrian 4. Schema definition classes will be different but probably query builder could be the same.

**Comment by rsim** [comment]
I am closing this now as no active work is planned for Mondrian 4 support.
