### ISSUE TITLE
Gem release?

### ISSUE THREAD

**Issue by jazzido** [rsim/mondrian-olap#42]
Would it be possible to upload a new release to RubyGems (`0.7.1` maybe?). There's been a number of useful fixes and dependency updates since b59e02a54ee82bc182e54edcc968200f50d5748c (last stable revision)

**Comment by rsim** [comment]
We recently made some extensions for drill through functionality and now are testing if that is working fine. If there will be no problems then I will release a new gem versions in the nearest days.

**Comment by jazzido** [comment]
Hi @rsim,

Sorry to bug again. Have you had the chance to cut a new gem? I've just released my project [`mondrian-rest` as a gem](http://rubygems.org/gems/mondrian-rest) and would love that it uses the latest version of `mondrian-olap` codebase. 

Thanks!

**Comment by rsim** [comment]
Thanks for the reminder :)

I just published the version 0.8.0.
