### ISSUE TITLE
Connecting to Snowflake data warehouse.

### ISSUE THREAD

**Issue by dsalazar-carecloud** [rsim/mondrian-olap#52]
Long time listener and big fan.  I was wondering if it was possible to connect to [Snowflake](https://docs.snowflake.net/manuals/user-guide/jdbc.html) data warehouse?  If possible what would this configuration look like?  Any guidance would be greatly appreciated.

**Comment by dsalazar-carecloud** [comment]
False alarm.  I dove into the connection.rb file and saw the ability to pass a jdbc string which worked.

**Comment by blijblijblij** [comment]
👍

**Comment by rsim** [comment]
Please comment here if you will manage to use mondrian-olap with Snowflake and if it will perform well. Mondrian tries to detect the SQL dialect that it should use and currently there is no specific Snowflake dialect included. Therefore I am wondering which dialect will be selected by Mondrian and if all Mondrian generated SQL will be correct and performant for Snowflake.

**Comment by dsalazar-carecloud** [comment]
Extremely sorry for the late response.  I will see if I can get one of my colleagues from the business intelligence team to comment with more detail since they are the ones actually evaluating it.  What I can say is that they ETL'd our whole production workload and, based on the initial reactions from the BI team, they are very pleased with the results.   Queries that took a very long time to complete in our current production environment is now returning very quickly.  All of this and not one single aggregation table was created.  In summation the results were so impressive that it looks like we may be going down the snowflake path in the not so distant future.

**Comment by rnunez-carecloud** [comment]
Hi Raimonds

I work with David Salazar (Previous comment) and part of the BI team.  The test we performed with SnowFlake was very successful.  The connection and queries generated by the driver work as expected and beyond.  We were very pleased with the connection performance as well as the integration with the SnowFlake environment.   On behalf of our team I will like to thank you for your support.
