### ISSUE TITLE
connect olap-mondrian with mysql 

### ISSUE THREAD

**Issue by Sakou-77** [rsim/mondrian-olap#74]
Cannot establish connection with db mysql using jdbc-mysql-8.0.17, error:
Mondrian::OLAP::Error: mondrian.olap.MondrianException: Mondrian Error:Internal error: Error while creating SQL connection: Jdbc=jdbc:mysql://localhost/chu_dw?useUnicode=yes&characterEncoding=UTF-8; JdbcUser=root
  wrap_native_exception at C:/jruby-9.2.12.0/lib/ruby/gems/shared/gems/mondrian-olap-1.1.0/lib/mondrian/olap/error.rb:24
                connect at C:/jruby-9.2.12.0/lib/ruby/gems/shared/gems/mondrian-olap-1.1.0/lib/mondrian/olap/connection.rb:21
                 create at C:/jruby-9.2.12.0/lib/ruby/gems/shared/gems/mondrian-olap-1.1.0/lib/mondrian/olap/connection.rb:6
Jruby and JDK:
jruby 9.2.12.0 (2.5.7) 2020-07-01 db01a49ba6 Java HotSpot(TM) 64-Bit Server VM 25.241-b07 on 1.8.0_241-b07 +jit [mswin32-x86_64]

is there any solution for this problem?

thank you.

**Comment by rsim** [comment]
Based on the error message it seems that MySQL JDBC driver could not connect to the specified database. Please verify that you use the correct JDBC driver version that matches the MySQL server and that the connection credentials are correct.
