### ISSUE TITLE
Measure returning scientific format

### ISSUE THREAD

**Issue by diegonogueira** [rsim/mondrian-olap#75]
Hi, 

I have the measure (postgres, m_price, int8) like this:

```ruby
  measure 'Price', column: 'm_price', aggregator: 'sum' format_string: '#,###.00'
```
But, the result is: 

```ruby
"values":[["0.149e4"],["0.873e5"],["0.19798e5"],["0.776e5"],["0.19282e7"],["0.974667e6"],["0.14370531e9"],["0.189603291e9"]]}
```
If I run the query on Pentaho Workbench Schema, I have the right results,

````
Row #0: 1.490,00
Row #1: 87.300,00
Row #2: 19.798,00
Row #3: 77.600,00
Row #4: 1.928.200,00
Row #5: 974.667,00
Row #6: 143.705.310,00
Row #7: 189.603.291,00
```

thanks,

**Comment by diegonogueira** [comment]
Update: If I change my type from int8 to int4, I don't receive the format in scientific, but I can't format using format string.

 ```ruby
"values":[[1490.0],[87300.0],[19798.0],[77600.0],[1928200.0],[974667.0],[143705310.0],[189603291.0]]}
```

**Comment by rsim** [comment]
Several questions:
* How do you get `"values"` as an array of strings? mondrian-olap query results `values` will be a Ruby array of Ruby numeric values. Please show the Ruby code that you use. How do you translate these numeric values to strings?
* If you use the `int8` data type then this can store only integers. Why do you use a decimal format string with two digits after the decimal point?
* And also it always helps if you tell which mondrian-olap version do you use - either a gem version or the latest code from the master.

**Comment by diegonogueira** [comment]
```yml
GEM
  remote: https://rubygems.org/
  specs:
    builder (3.2.4)
    jdbc-postgres (42.2.14)
    mondrian-olap (1.1.0)
      nokogiri
    nokogiri (1.10.10-java)
    rack (2.2.3)
```

```ruby
result = olap.execute(query)
result.values
```

Another alternative, formating on mdx.. but same results..

```sql
      WITH
      MEMBER [Measures].[FPrice] AS [Measures].[Price], FORMAT_STRING="$#,##0.00"
      SET [~ROWS] AS
        {[PurchaseCalendar.Year].[Year].Members}
      SELECT
        NON EMPTY {[Measures].[FPrice]} ON COLUMNS,
        NON EMPTY [~ROWS] ON ROWS
      FROM
        [Orders]
```

On postgres, I changed to numeric(10,2), but same results..

With the same query/xml, I can run on Saiku or Pentaho workbench.

It's seams that any format_string is being ignored..

**Comment by diegonogueira** [comment]
I found the problem.. I need to use ` formatted_values` instead of `values`... 
thanks, @rsim

**Comment by diegonogueira** [comment]
No.. it's not solved.. :(

```
"formatted_values":[["14.9"],["873"],["197.98"],["776"],["19,282"],["9,746.67"],["1,437,053.1"],["1,896,032.91"]],"values":[["0.149e2"],["0.873e3"],["0.19798e3"],["0.776e3"],["0.19282e5"],["0.974667e4"],["0.14370531e7"],["0.189603291e7"]]}
```

The formatted_values returns as string... and values scientific.. 
I'm using numeric(10,2) on postgres...

**Comment by diegonogueira** [comment]
@rsim I thing this line is converting to scientific https://github.com/rsim/mondrian-olap/blob/3a0d676bdc51957240966bcdab30db4cdfb2c000/lib/mondrian/olap/result.rb#L491

If I changed to 'value.to_f' seams to works.. but problably brokes another thing... 
Any idea?

**Comment by rsim** [comment]
`format_string` that you specify in Mondrian schema only affects how `formatted_values` (which are string representations of  numeric values) are returned. If you need to show the returned values in your UI then use `formatted_values`.

 `values` should be used if you want to do any other numeric calculations using these values. `java_to_ruby_value` method performs mapping of Java numeric types to the corresponding Ruby types. `java.math.BigDecimal` type values (which are arbitrary-precision decimal values) are converted to the corresponding Ruby BigDecimal type values. If they were converted to Float then high-precision values might be converted to lower precision float values.

It seems that you are converting `values` to JSON. By default BigDecimal values are converted to string (due to the same potential issue that high-precision values might lost their precision if converted to floats). If you still would prefer to represent BigDecimal values as floats in JSON then you can monkey-patch `as_json` method for BigDecimal.

Here is an example how we do it in our application by monkey-patching `as_json` for Float and BigDecimal:
```ruby
# Override that Infinity will be null in JSON results
class Float
  def as_json(options = nil)
    if finite?
      super(options)
    else
      nil.as_json(options)
    end
  end
end

# override that BigDecimal will be converted to JSON number
class BigDecimal
  def as_json(options = nil)
    if finite?
      self.to_f
    else
      nil.as_json(options)
    end
  end

  def encode_json(encoder)
    if finite?
      to_s
    else
      'null'
    end
  end
end
```

**Comment by diegonogueira** [comment]
Thanks. 
But, there something that I'm not understanding.. 

### Postgres

m_price numeric(10,2) type.

### Schema

```ruby
measure 'Price', column: 'm_price', aggregator: 'sum'
```

### MDX is:

```sql
WITH
SET [~ROWS] AS
    {[PurchaseCalendar.Year].[Year].Members}
SELECT
NON EMPTY {[Measures].[Price]} ON COLUMNS,
NON EMPTY [~ROWS] ON ROWS
FROM [Orders]
```

### lib/mondrian/olap/result.rb

I added some logs

```ruby
      def self.java_to_ruby_value(value, column_type = nil)
        puts value
        puts column_type
        case value
        when Numeric, String
          value
        when Java::JavaMath::BigDecimal
          BigDecimal(value.to_s)
        when Java::JavaSql::Clob
          clob_to_string(value)
        else
          value
        end
      end
```
And the results are:

```
873.00
197.98
776.00
19282.00
9746.67
1437053.10
1896032.91
```

### My app 

Before I converted to json

```ruby
  result = olap.execute(query)
  puts result.values
```
And the results are:

```
0.873e3
0.19798e3
0.776e3
0.19282e5
0.974667e4
0.14370531e7
0.189603291e7
```

The precision problem is only when we have some calculation, right? In this case, the Java already done the calculation and the method `java_to_ruby_value ` is only to display. (I THINK)

How do you do in this case? If you need to sum currency? Do you use this format (0.189603291e7) or use formatted_values?

Thanks so much! :)

**Comment by rsim** [comment]
In case of PostgreSQL JDBC driver decimal values are returned with `java.math.BigDecimal` and are transformed to Ruby `BigDecimal` values. If you want to perform calculations in Ruby then you can use directly these BigDecimal values:
```ruby
BigDecimal("123") + BigDecimal("456")
=> 0.579e3
```

If you inspect BigDecimal values then by default they are using the scientific notation for the string representation:
```ruby
BigDecimal("123").inspect
=> "0.123e3"
BigDecimal("123") + BigDecimal("456") == 579
=> true
```
but you should not use the default representation to show it to users. Format and show it to users as you need. But BigDecimal values do not know about any Mondrian formatting that you specified.

In our case we perform all calculations in MDX formulas and then show to users `formatted_values` or when we need to use float values (e.g. in chart libraries) then we cast values to float and use them.

I hope this clarifies you confusion.

**Comment by diegonogueira** [comment]
Thanks, @rsim! :)
