### ISSUE TITLE
Is it possible to change the timezone?

### ISSUE THREAD

**Issue by diegonogueira** [rsim/mondrian-olap#76]
What is the best approach to work with multiple timezones? 
I have dim_calendar and dim_timer dimensions (UTC), but depending of the user, I need to change the timezone to calculate and display data.

I did using KeyExpression

 ```
EXTRACT(
  HOUR FROM (
    time at time zone 'america/sao_paulo'
  ))
```

But, I don't know if is the best way.. 

Is it possible to pass the timezone on `schema`, `olap.execute` or before run the mdx queries (SET TIMEZONE='america/sao_paulo'); 

Thanks

**Comment by rsim** [comment]
There is no good solution for supporting different time zones for each user in one Mondrian schema. Dimension members are cached at the schema level and they cannot be different in each query.

In our application, we offer to specify one specific time zone for reporting purposes and then we convert all timestamps to the corresponding date entry in the time dimension.

One approach would be to have a date dimension and a separate hour dimension and store there UTC date and hour. But then when presenting query results to users you could dynamically replace UTC hour with the user time zone hour by adding the corresponding offset.
